FROM strt/nginx:base-development

# Add PHP settings
COPY ./data/snippets/php_fastcgi.conf /etc/nginx/snippets/php_fastcgi.conf

# Add our sites
COPY ./data/sites/development.conf /etc/nginx/sites-enabled/development.conf
